[package]
name = "twitter_bot01"
version = "0.1.0"
authors = ["pc <paraxite@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1.22"
reqwest = {version="0.9.20", default-features=false, features=["rustls-tls"]}
gif = "0.10.3"
rusttype = "0.8.1"
serde_json = "1.0.40"
rayon = "1.2.0"
rand = "0.7.2"
chrono = "0.4.9"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1